# Generated by Django 2.2.5 on 2019-09-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindililah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NeighborhoodName', models.CharField(max_length=100)),
                ('Location', models.TextField()),
                ('PopulationSaudiMale', models.IntegerField()),
                ('PopulationSaudiFemale', models.IntegerField()),
                ('PopulationNONSaudiMale', models.IntegerField()),
                ('PopulationNONSaudiFemale', models.IntegerField()),
                ('AveragePriceLands', models.IntegerField()),
                ('AveragePriceAprt', models.IntegerField()),
                ('AveragePriceVilla', models.IntegerField()),
                ('NumPrivateSchools', models.IntegerField()),
                ('NumPublicSchools', models.IntegerField()),
                ('NumParks', models.IntegerField()),
                ('NumHospitals', models.IntegerField()),
                ('NumBusStations', models.IntegerField()),
                ('NumTrainStations', models.IntegerField()),
            ],
        ),
    ]
